# REMEMBER TO CHANGE THE LOCATIONS 


[nt]
path = /lustre/work/ersharma/core_nt_blast/core_nt

[prefetch]
path = /opt/sratoolkit/bin/prefetch

[fastq-dump]
path = /opt/sratoolkit/bin/fastq-dump

[blastn]
path = /opt/ncbi-blast/bin/blastn

[make_blast_db]
path = /opt/ncbi-blast/bin/makeblastdb

[bwa]
path = /usr/bin/bwa

[samtools]
path = /usr/bin/samtools

[megahit]
path = python3 /opt/megahit/bin/megahit

[datasets]
path = /usr/local/bin/datasets
